package addrgen

func initData(g *Generator) {
	g.countries["US"] = &CountryDef{
		Name: "美国", Code: "US",
		PostFmt: "#####", PhonePrefix: "1", PhoneDigits: 10,
		FirstNames: []string{"James","Mary","John","Patricia","Robert","Jennifer","Michael","Linda","David","Barbara","William","Elizabeth","Richard","Susan","Joseph","Jessica","Thomas","Sarah","Christopher","Karen","Charles","Lisa","Daniel","Nancy","Matthew","Betty","Anthony","Margaret","Mark","Sandra","Steven","Ashley","Andrew","Dorothy","Kenneth","Kimberly","George","Emily","Edward","Donna","Brian","Michelle","Kevin","Carol","Jason","Amanda","Jeffrey","Melissa","Ryan","Deborah","Scott","Laura","Eric","Stephanie","Jacob","Rebecca","Nicholas","Sharon","Jonathan","Cynthia","Samuel","Kathleen","Frank","Amy","Brandon","Shirley","Raymond","Angela","Gregory","Anna","Joshua","Brenda","Jerry","Pamela","Tyler","Nicole","Aaron","Emma","Jose","Samantha","Nathan","Katherine","Timothy","Christina","Jordan","Virginia"},
		LastNames: []string{"Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Wilson","Anderson","Taylor","Thomas","Moore","Jackson","Martin","Lee","Thompson","White","Harris","Clark","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Hill","Green","Adams","Baker","Nelson","Carter","Mitchell","Roberts","Turner","Phillips","Campbell","Parker","Evans","Edwards","Collins","Stewart","Morris","Reed","Cook","Morgan","Bell","Murphy","Bailey","Rivera","Cooper","Richardson","Cox","Howard","Ward","Torres","Peterson","Gray","Ramirez","James","Watson","Brooks","Kelly","Sanders","Price","Bennett","Wood","Barnes","Ross","Henderson","Coleman","Jenkins","Perry","Powell","Long","Patterson","Hughes","Flores","Washington","Butler"},
		Cities: []CityDef{
			{"New York City","NY"},{"Los Angeles","CA"},{"Chicago","IL"},{"Houston","TX"},{"Phoenix","AZ"},{"Philadelphia","PA"},{"San Antonio","TX"},{"San Diego","CA"},{"Dallas","TX"},{"Austin","TX"},{"Jacksonville","FL"},{"Fort Worth","TX"},{"San Jose","CA"},{"Columbus","OH"},{"Charlotte","NC"},{"Indianapolis","IN"},{"San Francisco","CA"},{"Seattle","WA"},{"Denver","CO"},{"Nashville","TN"},{"Oklahoma City","OK"},{"El Paso","TX"},{"Washington","DC"},{"Boston","MA"},{"Las Vegas","NV"},{"Portland","OR"},{"Memphis","TN"},{"Louisville","KY"},{"Baltimore","MD"},{"Milwaukee","WI"},{"Albuquerque","NM"},{"Tucson","AZ"},{"Fresno","CA"},{"Sacramento","CA"},{"Mesa","AZ"},{"Kansas City","MO"},{"Atlanta","GA"},{"Omaha","NE"},{"Colorado Springs","CO"},{"Raleigh","NC"},{"Long Beach","CA"},{"Virginia Beach","VA"},{"Miami","FL"},{"Oakland","CA"},{"Minneapolis","MN"},{"Tampa","FL"},{"Tulsa","OK"},{"Arlington","TX"},{"New Orleans","LA"},{"Cleveland","OH"},{"Bakersfield","CA"},{"Honolulu","HI"},{"Anaheim","CA"},{"Santa Ana","CA"},{"Riverside","CA"},{"Corpus Christi","TX"},{"Lexington","KY"},{"Stockton","CA"},{"Henderson","NV"},{"Saint Paul","MN"},{"St. Louis","MO"},{"Cincinnati","OH"},{"Pittsburgh","PA"},{"Greensboro","NC"},{"Anchorage","AK"},{"Plano","TX"},{"Newark","NJ"},{"Lincoln","NE"},{"Orlando","FL"},{"Irvine","CA"},{"Toledo","OH"},{"Durham","NC"},{"Chula Vista","CA"},{"Fort Wayne","IN"},{"Jersey City","NJ"},{"St. Petersburg","FL"},{"Laredo","TX"},{"Madison","WI"},{"Chandler","AZ"},{"Buffalo","NY"},{"Lubbock","TX"},{"Scottsdale","AZ"},{"Reno","NV"},{"Glendale","AZ"},{"Gilbert","AZ"},{"Winston-Salem","NC"},{"North Las Vegas","NV"},{"Norfolk","VA"},{"Chesapeake","VA"},{"Garland","TX"},{"Fremont","CA"},{"Richmond","VA"},{"Boise","ID"},{"San Bernardino","CA"},{"Spokane","WA"},{"Yonkers","NY"},{"Modesto","CA"},{"Tacoma","WA"},{"Fontana","CA"},{"Des Moines","IA"},{"Birmingham","AL"},{"Little Rock","AR"},{"Salt Lake City","UT"},{"Providence","RI"},{"Rochester","NY"},{"Grand Rapids","MI"},{"Hartford","CT"},{"Manchester","NH"},{"Augusta","ME"},{"Charleston","WV"},{"Billings","MT"},{"Cheyenne","WY"},{"Fargo","ND"},{"Sioux Falls","SD"},{"Burlington","VT"},{"Dover","DE"},
		},
		Streets: []string{"Main St","Oak Ave","Elm St","Park Ave","Maple Dr","Cedar Ln","Pine St","Washington Blvd","Broadway","Lake Dr","Highland Ave","Sunset Blvd","River Rd","Lincoln Ave","Madison Ave","Franklin Blvd","Market St","Church St","School St","Forest Ave","Hill Rd","Walnut St","Meadow Ln","Spring St","Willow Dr","Cherry St","Rose Ave","Garden St","Locust Ave","Magnolia Ave","Cypress Ct","Birchwood Dr","Hemlock Ln","Ashwood Dr","Poplar Ave","Juniper Ct","Laurel Ln","Meadowbrook Dr","Sunrise Dr","Westwood Blvd","Northwood Dr","Southwood Dr","Eastwood Dr","Greenwood Ave","Fairview Ave","Pleasant St","Chestnut St","Walden Rd","Hickory Ln","Sycamore Dr","Dogwood Ave","Hollywood Blvd","Vine St","Mulberry St","Grove St","Mill St","Water St","State St","Adams St","Jefferson Ave","Monroe St","Jackson Ave","Washington St","Pennsylvania Ave","Massachusetts Ave","Connecticut Ave","Lexington Ave","Broad St","Central Ave","Union St","Liberty Ave","Commonwealth Ave","Cambridge Rd","Oxford St","Princeton Ave","Harvard Ave","Yale Ave","Stanford Ave","Riverside Dr","Harbor Blvd","Bayview Dr","Ocean Ave","Mountain Rd","Valley Blvd","Mountain View Ave","Pacific Ave","Atlantic Ave","Lakeshore Dr","Country Club Rd","Rolling Rd","Deerfield Dr"},
	}

	g.countries["GB"] = &CountryDef{
		Name: "英国", Code: "GB",
		PostFmt: "AA# #AA", PhonePrefix: "44", PhoneDigits: 10,
		FirstNames: []string{"Oliver","Amelia","George","Olivia","Harry","Isla","Noah","Emily","Jack","Ava","Charlie","Ella","Thomas","Jessica","James","Isabella","William","Mia","Henry","Poppy","Daniel","Sophie","Samuel","Lily","Joseph","Chloe","David","Grace","Benjamin","Evie","Archie","Freya","Theo","Alice","Leo","Florence","Oscar","Sienna","Arthur","Rosie","Alfie","Ivy","Joshua","Willow","Freddie","Phoebe","Ethan","Elsie","Mason","Holly","Harrison","Daisy","Lucas","Eleanor","Jacob","Rosa","Ewan","Maisie","Adam","Lola","Edward","Megan","Toby","Lilly","Finley","Molly","Jake","Mila","Dylan","Eliza","Luke","Isabelle","Callum","Aria","Stanley","Eva","Harvey","Millie"},
		LastNames: []string{"Smith","Jones","Williams","Taylor","Brown","Davies","Evans","Wilson","Thomas","Roberts","Johnson","Lewis","Walker","Robinson","Wood","Thompson","White","Watson","Jackson","Wright","Green","Harris","Cooper","King","Lee","Martin","Clarke","Turner","Hill","Baker","Hall","Ward","Allen","Young","Mitchell","Phillips","Anderson","Scott","Adams","James","Morgan","Griffiths","Hughes","Edwards","Reid","Murray","Parker","Fisher","Mason","Harrison","Foster","Richards","Cox","Webb","Palmer","Stevens","Walsh","Bennett","Gray","Marshall","Lloyd","Barnes","Dixon","Grant","Fox","Graham","Holmes","Bishop","Cole","Stone","Bradley","Watts","Fletcher","Black","Jenkins","Gibson","West","Russell"},
		Cities: []CityDef{
			{"London","ENG"},{"Birmingham","ENG"},{"Glasgow","SCT"},{"Manchester","ENG"},{"Sheffield","ENG"},{"Leeds","ENG"},{"Edinburgh","SCT"},{"Liverpool","ENG"},{"Bristol","ENG"},{"Cardiff","WLS"},{"Leicester","ENG"},{"Bradford","ENG"},{"Belfast","NIR"},{"Coventry","ENG"},{"Nottingham","ENG"},{"Reading","ENG"},{"Kingston upon Hull","ENG"},{"Preston","ENG"},{"Swansea","WLS"},{"Newcastle upon Tyne","ENG"},{"Brighton","ENG"},{"Derby","ENG"},{"Southampton","ENG"},{"Wolverhampton","ENG"},{"Plymouth","ENG"},{"Stoke-on-Trent","ENG"},{"Milton Keynes","ENG"},{"Northampton","ENG"},{"Aberdeen","SCT"},{"Portsmouth","ENG"},{"York","ENG"},{"Sunderland","ENG"},{"Luton","ENG"},{"Swindon","ENG"},{"Southend-on-Sea","ENG"},{"Walsall","ENG"},{"Bournemouth","ENG"},{"Peterborough","ENG"},{"Blackpool","ENG"},{"Dundee","SCT"},{"Middlesbrough","ENG"},{"Oxford","ENG"},{"Cambridge","ENG"},{"Norwich","ENG"},{"Exeter","ENG"},{"Bath","ENG"},{"Ipswich","ENG"},{"Gloucester","ENG"},{"Cheltenham","ENG"},{"Colchester","ENG"},{"Crawley","ENG"},{"Slough","ENG"},{"Wrexham","WLS"},{"Warrington","ENG"},{"Doncaster","ENG"},{"Rotherham","ENG"},{"Barnsley","ENG"},{"Wakefield","ENG"},{"Carlisle","ENG"},{"Chester","ENG"},{"Lincoln","ENG"},{"Worcester","ENG"},{"Hereford","ENG"},{"Salisbury","ENG"},{"Durham","ENG"},{"Canterbury","ENG"},{"Winchester","ENG"},{"Chichester","ENG"},{"Ely","ENG"},{"Ripon","ENG"},{"Truro","ENG"},{"Wells","ENG"},{"Lichfield","ENG"},{"St Albans","ENG"},{"Perth","SCT"},{"Stirling","SCT"},{"Inverness","SCT"},{"Newport","WLS"},{"Bangor","WLS"},{"St Davids","WLS"},{"Londonderry","NIR"},{"Armagh","NIR"},{"Lisburn","NIR"},{"Newry","NIR"},{"Barrow-in-Furness","ENG"},{"Blackburn","ENG"},{"Bolton","ENG"},{"Bournemouth","ENG"},{"Bracknell","ENG"},{"Carlisle","ENG"},{"Chelmsford","ENG"},{"Chesterfield","ENG"},{"Corby","ENG"},{"Crewe","ENG"},{"Darlington","ENG"},{"Dudley","ENG"},{"Eastbourne","ENG"},{"Gateshead","ENG"},{"Grimsby","ENG"},{"Halifax","ENG"},{"Harlow","ENG"},{"Harrogate","ENG"},{"Huddersfield","ENG"},{"Keighley","ENG"},{"Kettering","ENG"},{"Lancaster","ENG"},{"Leamington Spa","ENG"},{"Macclesfield","ENG"},{"Mansfield","ENG"},{"Nuneaton","ENG"},
		},
		Streets: []string{"High St","Station Rd","Main St","Church St","London Rd","Park Rd","Queen St","Victoria St","New Rd","Mill Rd","School Rd","Green Ln","King St","George St","Grove Rd","Manor Rd","Brook Ln","Mill Ln","West St","North St","South St","East St","Bridge St","Castle St","York Rd","Albert Rd","Oxford St","Regent St","Alexander Rd","Cambridge Rd","Bristol Rd","Chester Rd","Derby Rd","Durham Rd","Essex Rd","Gloucester Rd","Hereford Rd","Kent Rd","Lancaster Rd","Leicester Rd","Norfolk Rd","Suffolk Rd","Surrey Rd","Sussex Rd","Windsor Rd","Cornwall Rd","Devon Rd","Dorset Rd","Hampshire Rd","Rutland Rd","Warwick Rd","Wilton Rd","Belmont Rd","Clarence St","Duke St","Guildford Rd","Kingston Rd","Richmond Rd","The Crescent","The Green","The Grove","The Avenue","The Drive","The Chase","Meadow Way","Willow Way","Cedar Way","Birch Way","Maple Way","Ash Way","Butts Rd","Back Ln","Fen Ln","Marsh Ln","Heath Rd","Moor Ln","Common Rd","Great North Rd","London Rd","Watford Way","Barnet Rd","Finchley Rd","Holloway Rd","Edgware Rd","Harrow Rd","Wembley Rd","Ealing Rd"},
	}

	g.countries["CA"] = &CountryDef{
		Name: "加拿大", Code: "CA",
		PostFmt: "A#A #A#", PhonePrefix: "1", PhoneDigits: 10,
		FirstNames: []string{"Liam","Olivia","Noah","Emma","Oliver","Charlotte","William","Ava","James","Sophia","Benjamin","Amelia","Lucas","Mia","Henry","Harper","Alexander","Evelyn","Owen","Abigail","Logan","Emily","Ethan","Ella","Jacob","Madison","Ryan","Scarlett","Nathan","Aria","Matthew","Chloe","Dylan","Grace","Jack","Zoey","Sebastian","Avery","Caleb","Riley","Jackson","Hannah","Aiden","Ellie","Mason","Isabella","Ethan","Maya","Max","Sarah","Samuel","Victoria","Luke","Lily","Jayden","Natalie","Evan","Sophie","Daniel","Zoe","Carter","Leah","Isaac","Hailey","Connor","Audrey","Lincoln","Julia","Wyatt","Savannah"},
		LastNames: []string{"Smith","Brown","Tremblay","Johnson","Wilson","Lee","Martin","Taylor","White","Gagnon","Anderson","Williams","Jones","Cote","Miller","Gauthier","Thompson","Robinson","Roy","Clark","Campbell","Young","Scott","Zhang","King","Morin","MacDonald","Reid","Leclerc","Murray","Wong","Chen","Lewis","Singh","Patel","Wright","Baker","Moore","Pelletier","Adams","Li","Wang","Ferguson","Leblanc","Ouellet","Bouchard","Lavoie","Fortin","Caron","Belanger","Pelletier","Paquette","Lessard","St-Pierre","Poirier","Michaud","Richard","Girard","Moreau","Landry","Rousseau","Bergeron","Beaulieu","Dupuis","Clement","Charbonneau","Desjardins","Fournier","Lapointe","Gosselin"},
		Cities: []CityDef{
			{"Toronto","ON"},{"Montreal","QC"},{"Calgary","AB"},{"Ottawa","ON"},{"Edmonton","AB"},{"Winnipeg","MB"},{"Mississauga","ON"},{"Vancouver","BC"},{"Brampton","ON"},{"Hamilton","ON"},{"Surrey","BC"},{"Quebec City","QC"},{"Halifax","NS"},{"Laval","QC"},{"London","ON"},{"Markham","ON"},{"Vaughan","ON"},{"Gatineau","QC"},{"Victoria","BC"},{"Saskatoon","SK"},{"Kitchener","ON"},{"Burnaby","BC"},{"Windsor","ON"},{"Longueuil","QC"},{"Regina","SK"},{"Oakville","ON"},{"Richmond","BC"},{"Burlington","ON"},{"Oshawa","ON"},{"Greater Sudbury","ON"},{"Barrie","ON"},{"St. Catharines","ON"},{"Sherbrooke","QC"},{"Guelph","ON"},{"Levis","QC"},{"Trois-Rivieres","QC"},{"Chatham-Kent","ON"},{"Cambridge","ON"},{"Kingston","ON"},{"Coquitlam","BC"},{"Thunder Bay","ON"},{"Whitehorse","YT"},{"Yellowknife","NT"},{"Iqaluit","NU"},{"Charlottetown","PE"},{"St. John's","NL"},{"Fredericton","NB"},{"Moncton","NB"},{"Saint John","NB"},{"Sydney","NS"},{"Kelowna","BC"},{"Abbotsford","BC"},{"Nanaimo","BC"},{"Prince George","BC"},{"Kamloops","BC"},{"Chilliwack","BC"},{"Maple Ridge","BC"},{"Delta","BC"},{"Langley","BC"},{"North Vancouver","BC"},{"Lethbridge","AB"},{"Red Deer","AB"},{"Medicine Hat","AB"},{"Airdrie","AB"},{"Fort McMurray","AB"},{"Grande Prairie","AB"},{"Moose Jaw","SK"},{"Prince Albert","SK"},{"Brandon","MB"},{"Sault Ste. Marie","ON"},{"Peterborough","ON"},{"Belleville","ON"},{"Pickering","ON"},{"Ajax","ON"},{"Milton","ON"},{"Halton Hills","ON"},{"Newmarket","ON"},{"St. Thomas","ON"},{"Cape Breton","NS"},{"Truro","NS"},{"Summerside","PE"},{"Corner Brook","NL"},{"Labrador City","NL"},
		},
		Streets: []string{"Main St","Bay St","King St","Queen St","Yonge St","Bloor St","Dundas St","Front St","Church St","Spadina Ave","Bathurst St","Lake Shore Blvd","Steeles Ave","Finch Ave","Sheppard Ave","Don Mills Rd","Maple Ave","Cedar Ave","Elm St","Oak St","Jarvis St","College St","Carlton St","Wellesley St","Adelaide St","Richmond St","University Ave","Bayview Ave","Leslie St","Victoria Park Ave","Kennedy Rd","McCowan Rd","Markham Rd","Warden Ave","Birchmount Rd","Pharmacy Ave","Kipling Ave","Islington Ave","Royal York Rd","Jane St","Keele St","Dufferin St","Roncesvalles Ave","Lakeshore Blvd","Gardiner Expy","Don Valley Pkwy","Portage Ave","Osborne St","Pembina Hwy","McPhillips St","Robson St","Granville St","Georgia St","Burrard St","Hastings St","Broadway","Cambie St","Oak St","Marine Dr","Kingsway","St Catherine St","Peel St","Sherbrooke St","Maisonneuve Blvd","Decarie Blvd","Cote des Neiges Rd","Rachel St","Parc Ave","St Denis St","Papineau Ave"},
	}

	g.countries["AU"] = &CountryDef{
		Name: "澳大利亚", Code: "AU",
		PostFmt: "####", PhonePrefix: "61", PhoneDigits: 9,
		FirstNames: []string{"Oliver","Charlotte","William","Olivia","Jack","Mia","Noah","Amelia","Thomas","Isla","James","Ava","Henry","Grace","Ethan","Sophie","Leo","Chloe","Lucas","Emily","Charlie","Harper","Harrison","Ella","Lachlan","Zoe","Hugo","Sarah","Alexander","Lily","Max","Evie","Archie","Matilda","Samuel","Abigail","Benjamin","Ruby","Daniel","Scarlett","Ryan","Willow","Riley","Mackenzie","Cooper","Sienna","Liam","Aria","Mason","Piper","Joshua","Isabelle","Jake","Molly","Dylan","Summer","Luke","Ivy","Blake","Georgia","Declan","Indie","Nathan","Imogen","Xavier","Hayley","Sebastian","Billie","Caleb","Mila"},
		LastNames: []string{"Smith","Jones","Williams","Brown","Wilson","Taylor","Johnson","Lee","White","Anderson","Thomas","Harris","Martin","Thompson","Robinson","Walker","Clark","Wright","Kelly","Turner","Evans","Green","Hill","Cooper","Baker","Reid","Mitchell","Cook","Carter","Phillips","Campbell","Murray","Miller","Allen","Davies","Scott","Young","Adams","Moore","King","Ward","O'Brien","Ryan","Morgan","Watson","Jackson","Bennett","Foster","Parker","Cox","Gray","Russell","Roberts","Dixon","Bailey","Marshall","Griffiths","Watts","Price","Grant","Fisher","Hayes","Graham","Rogers","Ellis","Stevens","Murphy","Hughes","Webb","Perry","Knight","Fox","Palmer","Berry"},
		Cities: []CityDef{
			{"Sydney","NSW"},{"Melbourne","VIC"},{"Brisbane","QLD"},{"Perth","WA"},{"Adelaide","SA"},{"Gold Coast","QLD"},{"Newcastle","NSW"},{"Sunshine Coast","QLD"},{"Canberra","ACT"},{"Central Coast","NSW"},{"Logan City","QLD"},{"Geelong","VIC"},{"Wollongong","NSW"},{"Hobart","TAS"},{"Townsville","QLD"},{"Cairns","QLD"},{"Toowoomba","QLD"},{"Darwin","NT"},{"Ballarat","VIC"},{"Mandurah","WA"},{"Bendigo","VIC"},{"Launceston","TAS"},{"Mackay","QLD"},{"Rockhampton","QLD"},{"Coffs Harbour","NSW"},{"Bunbury","WA"},{"Bundaberg","QLD"},{"Hervey Bay","QLD"},{"Wagga Wagga","NSW"},{"Shepparton","VIC"},{"Albury","NSW"},{"Port Macquarie","NSW"},{"Orange","NSW"},{"Dubbo","NSW"},{"Tamworth","NSW"},{"Armidale","NSW"},{"Mildura","VIC"},{"Mount Gambier","SA"},{"Whyalla","SA"},{"Port Lincoln","SA"},{"Geraldton","WA"},{"Albany","WA"},{"Kalgoorlie","WA"},{"Broome","WA"},{"Alice Springs","NT"},{"Katherine","NT"},{"Burnie","TAS"},{"Devonport","TAS"},{"Cessnock","NSW"},{"Bathurst","NSW"},{"Lismore","NSW"},{"Taree","NSW"},{"Goulburn","NSW"},{"Nowra","NSW"},{"Griffith","NSW"},{"Broken Hill","NSW"},{"Wangaratta","VIC"},{"Traralgon","VIC"},{"Warrnambool","VIC"},{"Sale","VIC"},{"Horsham","VIC"},{"Moe","VIC"},{"Gawler","SA"},{"Murray Bridge","SA"},{"Ipswich","QLD"},{"Redcliffe","QLD"},{"Caloundra","QLD"},{"Gympie","QLD"},{"Warwick","QLD"},{"Dalby","QLD"},{"Mount Isa","QLD"},{"Gladstone","QLD"},{"Maryborough","QLD"},{"Fremantle","WA"},{"Joondalup","WA"},{"Rockingham","WA"},{"South Perth","WA"},{"Nedlands","WA"},{"Subiaco","WA"},
		},
		Streets: []string{"George St","Elizabeth St","King St","Queen St","William St","Pitt St","Market St","Bourke St","Swanston St","Collins St","Flinders St","Chapel St","Edward St","Albert St","Victoria Rd","Pacific Hwy","Main St","High St","Station St","The Esplanade","Anzac Parade","Darling Dr","Macquarie St","Oxford St","Crown St","Campbell St","Broadway","Parramatta Rd","Canterbury Rd","Hume Hwy","Princes Hwy","Great Western Hwy","New South Head Rd","Old South Head Rd","Bondi Rd","Bronte Rd","Coogee Bay Rd","St Kilda Rd","Brunswick St","Lygon St","Sydney Rd","Nicholson St","Toorak Rd","Glenferrie Rd","Burwood Hwy","Springvale Rd","Dandenong Rd","Fitzgerald St","Stirling St","Hay St","Adelaide Terrace","Beaufort St","Canning Hwy","Albany Hwy","Great Eastern Hwy","Nicholson Rd","Wanneroo Rd","Grey St","Wickham St","Margaret St","Wharf St","Charlotte St","Albert St","Creek St","Dockland Dr","Customs St","Eagle St"},
	}

	g.countries["DE"] = &CountryDef{
		Name: "德国", Code: "DE",
		PostFmt: "#####", PhonePrefix: "49", PhoneDigits: 10,
		FirstNames: []string{"Emma","Mia","Hanna","Anna","Lea","Lina","Sophie","Marie","Emilie","Laura","Nele","Lena","Johanna","Lara","Paula","Nora","Amelie","Sarah","Clara","Lisa","Ben","Jonas","Leon","Lukas","Finn","Noah","Elias","Luis","Maximilian","Felix","Paul","Tom","Tim","Niklas","Luca","Julian","Philipp","Fabian","Jan","Moritz","David","Lennart","Matteo","Liam","Marlon","Jannis","Linus","Fiete","Mats","Jasper","Nico","Fritz","Peer","Sven","Ralf","Bernd","Manfred","Heiko","Carsten","Ulrich","Frank","Jens","Ruediger","Burkhard","Wilfried","Gerd","Albrecht","Eckhard","Detlef","Volker","Rainer","Gerhard","Ernst","Klaus","Dieter","Wolfgang"},
		LastNames: []string{"Schmidt","Mueller","Weber","Fischer","Meyer","Schulz","Wagner","Becker","Hoffmann","Schaefer","Koch","Bauer","Richter","Klein","Wolf","Schroeder","Neumann","Schwarz","Zimmermann","Braun","Krueger","Hofmann","Hartmann","Lange","Schmitt","Werner","Schmitz","Krause","Maier","Lehmann","Huber","Kaiser","Herrmann","Fuchs","Peters","Lang","Scholz","Moeller","Weiss","Jung","Heinrich","Haase","Seidel","Ludwig","Schubert","Vogel","Franke","Koenig","Winkler","Roth","Bergmann","Jansen","Busch","Baumann","Koehler","Pohl","Jahn","Reuter","Kern","Voigt","Bartsch","Engel","Boehm","Gottschalk","Rieger","Uhl","Rupp","Betz","Krebs","Herbst","Schoen","Seiler","Frey"},
		Cities: []CityDef{
			{"Berlin","BE"},{"Hamburg","HH"},{"Munich","BY"},{"Cologne","NW"},{"Frankfurt am Main","HE"},{"Duesseldorf","NW"},{"Stuttgart","BW"},{"Essen","NW"},{"Dortmund","NW"},{"Dresden","SN"},{"Bremen","HB"},{"Nuremberg","BY"},{"Hannover","NI"},{"Leipzig","SN"},{"Duisburg","NW"},{"Bochum","NW"},{"Wuppertal","NW"},{"Bielefeld","NW"},{"Bonn","NW"},{"Muenster","NW"},{"Mannheim","BW"},{"Augsburg","BY"},{"Wiesbaden","HE"},{"Karlsruhe","BW"},{"Gelsenkirchen","NW"},{"Aachen","NW"},{"Moenchengladbach","NW"},{"Kiel","SH"},{"Chemnitz","SN"},{"Braunschweig","NI"},{"Halle","ST"},{"Magdeburg","ST"},{"Freiburg","BW"},{"Krefeld","NW"},{"Mainz","RP"},{"Luebeck","SH"},{"Erfurt","TH"},{"Oberhausen","NW"},{"Rostock","MV"},{"Kassel","HE"},{"Hagen","NW"},{"Potsdam","BB"},{"Saarbruecken","SL"},{"Oldenburg","NI"},{"Hamm","NW"},{"Ludwigshafen","RP"},{"Osnabrueck","NI"},{"Leverkusen","NW"},{"Heidelberg","BW"},{"Darmstadt","HE"},{"Solingen","NW"},{"Regensburg","BY"},{"Paderborn","NW"},{"Ingolstadt","BY"},{"Wuerzburg","BY"},{"Wolfsburg","NI"},{"Ulm","BW"},{"Goettingen","NI"},{"Bottrop","NW"},{"Remscheid","NW"},{"Recklinghausen","NW"},{"Bremerhaven","HB"},{"Reutlingen","BW"},{"Koblenz","RP"},{"Bergisch Gladbach","NW"},{"Jena","TH"},{"Troisdorf","NW"},{"Trier","RP"},{"Siegen","NW"},{"Cottbus","BB"},{"Celle","NI"},{"Hildesheim","NI"},{"Salzgitter","NI"},{"Heilbronn","BW"},{"Pforzheim","BW"},{"Bamberg","BY"},{"Worms","RP"},{"Neuss","NW"},{"Marl","NW"},{"Flensburg","SH"},{"Esslingen","BW"},{"Tuebingen","BW"},{"Ratingen","NW"},{"Luenen","NW"},{"Konstanz","BW"},{"Hanau","HE"},{"Lingen","NI"},{"Minden","NW"},{"Wilhelmshaven","NI"},{"Villingen-Schwenningen","BW"},{"Speyer","RP"},{"Passau","BY"},{"Frankfurt (Oder)","BB"},{"Landshut","BY"},{"Stralsund","MV"},{"Greifswald","MV"},{"Weimar","TH"},{"Gera","TH"},{"Zwickau","SN"},{"Plauen","SN"},{"Muelheim an der Ruhr","NW"},{"Herne","NW"},{"Velbert","NW"},{"Wesel","NW"},
		},
		Streets: []string{"Hauptstrasse","Schulstrasse","Bahnhofstrasse","Kirchstrasse","Gartenstrasse","Bergstrasse","Muehlenstrasse","Feldstrasse","Waldstrasse","Dorfstrasse","Ringstrasse","Parkstrasse","Poststrasse","Rathausstrasse","Berliner Str","Frankfurter Str","Friedrichstrasse","Goethestrasse","Schillerstrasse","Bismarckstrasse","Wilhelmstrasse","Ludwigstrasse","Blumenstrasse","Brunnenstrasse","Burgstrasse","Erlenstrasse","Finkenweg","Am Anger","Am Bahnhof","Am Markt","Am Muehlenberg","Am Pfarrgarten","Am Sportplatz","Auf dem Berg","Auf dem Felde","Hinterm Dorf","Im Grund","Im Wiesental","In den Gaerten","Mittelweg","Neue Str","Obere Str","Sandweg","Talstrasse","Untere Str","Vor dem Tor","Zur Muehle","Zur Heide","Zum Wiesengrund","Alte Str","Am Bach","Amselweg","Birkenweg","Buchenweg","Eichenweg","Fasanenweg","Fichtenweg","Hirschweg","Kastanienweg","Lerchenweg","Lindenstrasse","Rosenweg","Tannenweg","Ulmenweg","Weidenweg","Wiesenweg","Achenbachstr","Gartenfeldstr","Heinrich-Heine-Str","Hermann-Loens-Str","Jahnstrasse","Kantstrasse","Lessingstrasse","Lortzingstrasse","Mozartstrasse","Froebelstr","Pestalozzistr","Schubertstrasse","Wagnerstrasse","Uhlandstrasse","Adalbertstr","Bodelschwinghstr","Gneisenaustr","Kreuzbergstr","Yorckstr"},
	}

	g.countries["FR"] = &CountryDef{
		Name: "法国", Code: "FR",
		PostFmt: "#####", PhonePrefix: "33", PhoneDigits: 9,
		FirstNames: []string{"Lucas","Emma","Leo","Camille","Louis","Lina","Mael","Jade","Gabriel","Louise","Jules","Manon","Hugo","Zoe","Arthur","Lena","Raphael","Alice","Nathan","Sarah","Adam","Mila","Alexandre","Eva","Rayan","Rose","Tom","Chloe","Antoine","Noemie","Mathis","Lea","Maxime","Ines","Nolan","Juliette","Lorenzo","Maeva","Evan","Anais","Bastien","Clara","Sacha","Jeanne","Theo","Elisa","Mathieu","Maya","Baptiste","Romane","Quentin","Louane","Victor","Lola","Remi","Julia","Dorian","Celia","Clement","Heloise","Valentin","Maelle","Florian","Elena","Julien","Sofia","Tristan","Margaux","Matheo","Lise","Corentin","Oceane"},
		LastNames: []string{"Martin","Bernard","Dubois","Thomas","Robert","Richard","Petit","Durand","Leroy","Moreau","Simon","Laurent","Lefebvre","Michel","Garcia","David","Bertrand","Roux","Vincent","Fournier","Morel","Girard","Andre","Mercier","Dupont","Lambert","Bonnet","Francois","Martinez","Legrand","Garnier","Faure","Rousseau","Blanc","Guerin","Muller","Henry","Roussel","Nicolas","Perrin","Morin","Mathieu","Clement","Gauthier","Dumont","Lopez","Fontaine","Picard","Marie","Robin","Rolland","Leclercq","Philippe","Bourgeois","Chevalier","Renard","Gilles","Barbier","Charpentier","Da silva","Vasseur","Lemaire","Prevost","Millet","Gay","Lemaitre","Rey","Dufour","Colin","Maillard","Guillaume","Goncalves"},
		Cities: []CityDef{
			{"Paris","IDF"},{"Marseille","PAC"},{"Lyon","ARA"},{"Toulouse","OCC"},{"Nice","PAC"},{"Nantes","Pays"},{"Strasbourg","Grand"},{"Bordeaux","NAQ"},{"Montpellier","OCC"},{"Lille","HDF"},{"Rennes","BRE"},{"Reims","Grand"},{"Le Havre","Norm"},{"Saint-Etienne","ARA"},{"Toulon","PAC"},{"Angers","Pays"},{"Dijon","BFC"},{"Grenoble","ARA"},{"Nimes","OCC"},{"Clermont-Ferrand","ARA"},{"Aix-en-Provence","PAC"},{"Brest","BRE"},{"Le Mans","Pays"},{"Amiens","HDF"},{"Tours","CVL"},{"Limoges","NAQ"},{"Villeurbanne","ARA"},{"Metz","Grand"},{"Besancon","BFC"},{"Perpignan","OCC"},{"Orleans","CVL"},{"Caen","Norm"},{"Mulhouse","Grand"},{"Nancy","Grand"},{"Rouen","Norm"},{"Boulogne-Billancourt","IDF"},{"Argenteuil","IDF"},{"Montreuil","IDF"},{"Poitiers","NAQ"},{"Avignon","PAC"},{"Creteil","IDF"},{"Pau","NAQ"},{"Colombes","IDF"},{"Calais","HDF"},{"Dunkerque","HDF"},{"La Rochelle","NAQ"},{"Merignac","NAQ"},{"Aulnay-sous-Bois","IDF"},{"Bourg-en-Bresse","ARA"},{"Valence","ARA"},{"Annecy","ARA"},{"Chambery","ARA"},{"Bastia","COR"},{"Ajaccio","COR"},{"Chartres","CVL"},{"Bourges","CVL"},{"Blois","CVL"},{"Macon","BFC"},{"Auxerre","BFC"},{"Nevers","BFC"},{"Troyes","Grand"},{"Charleville-Mezieres","Grand"},{"Chaumont","Grand"},{"Chalons-en-Champagne","Grand"},{"Bar-le-Duc","Grand"},{"Albi","OCC"},{"Carcassonne","OCC"},{"Tarbes","OCC"},{"Foix","OCC"},{"Montauban","OCC"},{"Rodez","OCC"},{"Pamiers","OCC"},{"Cahors","OCC"},{"Auch","OCC"},{"Mende","OCC"},{"Laval","Pays"},{"La Roche-sur-Yon","Pays"},{"Saint-Brieuc","BRE"},{"Vannes","BRE"},{"Quimper","BRE"},{"Lorient","BRE"},{"Saint-Malo","BRE"},{"Evreux","Norm"},{"Alencon","Norm"},{"Cherbourg","Norm"},{"Saint-Lo","Norm"},{"Beauvais","HDF"},{"Laon","HDF"},{"Compiegne","HDF"},{"Soissons","HDF"},{"Abbeville","HDF"},{"Evry","IDF"},{"Pontoise","IDF"},{"Melun","IDF"},{"Meaux","IDF"},{"Rambouillet","IDF"},{"Fontainebleau","IDF"},{"Versailles","IDF"},{"Saint-Denis","IDF"},{"Nanterre","IDF"},
		},
		Streets: []string{"Rue de la Republique","Rue du General de Gaulle","Rue Jean Jaures","Rue Victor Hugo","Rue Pasteur","Rue Gambetta","Rue Carnot","Place de la Mairie","Place de la Republique","Place de l'Eglise","Boulevard de la Liberte","Avenue de la Gare","Avenue Jean Jaures","Rue des Ecoles","Rue du Moulin","Rue des Fleurs","Rue du Commerce","Rue de Paris","Rue de Lyon","Rue de Marseille","Rue de Bordeaux","Rue de Lille","Rue de Nantes","Rue de Strasbourg","Rue de Toulouse","Rue de Nice","Rue de Rennes","Rue de Dijon","Avenue de la Paix","Boulevard Haussmann","Boulevard Saint-Michel","Rue de Rivoli","Rue du Faubourg Saint-Honore","Avenue des Champs-Elysees","Place de l'Opera","Rue de la Paix","Rue Saint-Honore","Boulevard Saint-Germain","Quai de la Loire","Rue des Martyrs","Rue de Belleville","Rue Oberkampf","Rue de la Roquette","Rue de Charonne","Rue du Cherche-Midi","Rue de Vaugirard","Rue de Rennes","Rue Madame","Rue du Bac","Rue de Grenelle","Rue de Sevres","Rue de Babylone","Rue du Dragon","Rue Bonaparte","Rue de l'Universite","Rue de Lille","Rue Saint-Dominique","Avenue de Breteuil","Avenue de Villars","Rue de la Convention","Rue Lecourbe","Rue de la Croix Nivert","Avenue Emile Zola","Rue du Commerce","Rue de Vouille","Rue des Entrepreneurs","Rue Saint-Charles","Rue de Lourmel","Boulevard de Grenelle","Quai de Javel","Rue de la Comete","Rue de la Pompe","Rue de Passy","Avenue Mozart","Rue d'Auteuil","Boulevard Murat","Rue Michel-Ange","Place de l'Etoile","Avenue de la Grande Armee","Boulevard Pereire"},
	}

	g.countries["JP"] = &CountryDef{
		Name: "日本", Code: "JP",
		PostFmt: "###-####", PhonePrefix: "81", PhoneDigits: 10,
		FirstNames: []string{"Haruto","Sakura","Yuto","Hinata","Sota","Yui","Riku","Aoi","Sho","Minami","Kaito","Rin","Takumi","Mei","Kenta","Yuna","Sora","Miyu","Yuki","Mao","Kazuki","Nana","Daiki","Airi","Ryo","Koharu","Yamato","Moe","Ryota","Chihiro","Tsubasa","Riko","Itsuki","Fuka","Hayato","Nagi","Ren","Ayaka","Hiroto","Sara","Sosuke","Miyabi","Kohei","Azusa","Shinji","Kaori","Kenji","Misaki","Takeshi","Akari","Shohei","Tomomi","Masato","Erika","Keita","Manami","Yoshio","Haruka","Tetsuya","Risa","Hiroshi","Yoshie","Susumu","Yoshimi","Ryosuke","Mitsuki","Kazuhiro","Reina","Kunio","Natsumi","Shigeru","Kyoko","Shun","Mari"},
		LastNames: []string{"Sato","Suzuki","Takahashi","Tanaka","Watanabe","Ito","Yamamoto","Nakamura","Ohno","Kobayashi","Kato","Yoshida","Yamada","Sasaki","Yamaguchi","Matsumoto","Inoue","Kimura","Hayashi","Shimizu","Yamazaki","Mori","Abe","Ikeda","Hashimoto","Yamashita","Ishikawa","Nakajima","Maeda","Fujita","Ogawa","Goto","Okada","Hasegawa","Harada","Matsuda","Takagi","Sakai","Kondo","Miura","Kudo","Okamura","Shimada","Ueda","Nakagawa","Ota","Murata","Fujii","Saito","Kikuchi","Sakamoto","Imai","Ishii","Taguchi","Otsuka","Noguchi","Taniguchi","Kawamura","Nishimura","Sugiyama","Endo","Fukuda","Wada","Ueno","Nakashima","Hirano","Maruyama","Terada","Kojima","Shibata","Sano","Igarashi","Arai"},
		Cities: []CityDef{
			{"Tokyo","13"},{"Yokohama","14"},{"Osaka","27"},{"Nagoya","23"},{"Sapporo","01"},{"Fukuoka","40"},{"Kawasaki","14"},{"Kobe","28"},{"Kyoto","26"},{"Saitama","11"},{"Hiroshima","34"},{"Sendai","04"},{"Chiba","12"},{"Kitakyushu","40"},{"Sakai","27"},{"Niigata","15"},{"Hamamatsu","22"},{"Kumamoto","43"},{"Okayama","33"},{"Sagamihara","14"},{"Shizuoka","22"},{"Kawaguchi","11"},{"Kagoshima","46"},{"Hachioji","13"},{"Himeji","28"},{"Utsunomiya","09"},{"Matsuyama","38"},{"Matsudo","12"},{"Kawagoe","11"},{"Ichikawa","12"},{"Takamatsu","37"},{"Kurume","40"},{"Oita","44"},{"Toyota","23"},{"Fukuyama","34"},{"Nagasaki","42"},{"Toyohashi","23"},{"Gifu","21"},{"Kochi","39"},{"Miyazaki","45"},{"Nara","29"},{"Toyama","16"},{"Wakayama","30"},{"Maebashi","10"},{"Akita","05"},{"Aomori","02"},{"Morioka","03"},{"Fukushima","07"},{"Kanazawa","17"},{"Nagano","20"},{"Tsu","24"},{"Tottori","31"},{"Tokushima","36"},{"Yamaguchi","35"},{"Yamanashi-Kofu","19"},{"Saga","41"},{"Otsu","25"},{"Mito","08"},{"Takasaki","10"},{"Iwaki","07"},{"Asahikawa","01"},{"Hirosaki","02"},{"Hachinohe","02"},{"Koriyama","07"},{"Fujisawa","14"},{"Kashiwa","12"},{"Atsugi","14"},{"Urayasu","12"},{"Tokorozawa","11"},{"Ageo","11"},{"Kasukabe","11"},{"Toda","11"},{"Tachikawa","13"},{"Musashino","13"},{"Fuchu","13"},{"Kokubunji","13"},{"Koganei","13"},{"Kunitachi","13"},{"Fussa","13"},{"Kodaira","13"},{"Higashimurayama","13"},{"Higashikurume","13"},{"Kiyose","13"},{"Nishitokyo","13"},{"Setagaya","13"},{"Meguro","13"},{"Shinjuku","13"},{"Shibuya","13"},{"Shinagawa","13"},{"Ota","13"},{"Adachi","13"},{"Katsushika","13"},{"Sumida","13"},{"Taito","13"},{"Chuo","13"},{"Bunkyo","13"},{"Toshima","13"},{"Nakano","13"},{"Suginami","13"},{"Edogawa","13"},{"Arakawa","13"},{"Itabashi","13"},{"Nerima","13"},
		},
		Streets: []string{"Miyamoto Cho","Sakura Dori","Chuo Dori","Eki Mae Dori","Oo Dori","Kaigan Dori","Kita Dori","Minami Dori","Higashi Dori","Nishi Dori","Omotesando","Yamate Dori","Aoyama Dori","Meiji Dori","Showa Dori","Kasuga Dori","Hongo Dori","Koshu Kaido","Kanpachi Dori","Tamagawa Dori","Kannana Dori","Sotobori Dori","Uchibori Dori","Harumi Dori","Eitai Dori","Shinohashi Dori","Kiyosumi Dori","Gaien Nishi Dori","Roppongi Dori","Ichinohashi Dori","Shuto Expressway","Kandabashi Jinja Dori","Sakuragaoka","Fuji no Dori","Hanamizuki Dori","Keyaki Dori","Icho Namiki","Kumanocho","Matsubara Dori","Nakamise Dori","Denboin Dori","Shin Nakamise","Kaminarimon Dori","Asakusa Dori","Kototoi Dori","Zojinji Dori","Sanya Dori","Yokozuna Dori","Edo Dori","Hakozaki Dori","Tatara Dori","Hakataeki Chuogai","Watanabe Dori","Meinohama Dori","Momo Chi Dori","Kego Dori","Daimyo Dori","Imaizumi Dori","Yakuin Dori","Takamatsu Dori","Fukuoka Dori","Oyafuko Dori","Shintencho Dori","Kawabatadori","Tenjin Nishi Dori","Tenjin Higashi Dori","Akasaka Dori","Midori Dori","Koen Dori","Ishizaka Dori","Nagaragawa Dori","Otsu Dori","Marutamachi Dori","Imadegawa Dori","Shijo Dori","Gojo Dori","Kujo Dori","Nijo Dori","Ichijo Dori","Sanjo Dori","Horikawa Dori","Karasuma Dori","Kawaramachi Dori","Teramachi Dori","Muromachi Dori"},
	}

	g.countries["CN"] = &CountryDef{
		Name: "中国", Code: "CN",
		PostFmt: "######", PhonePrefix: "86", PhoneDigits: 11,
		FirstNames: []string{"伟","丽","明","强","静","磊","娜","军","洋","婷","勇","敏","杰","芳","涛","超","雪","燕","鹏","斌","丹","洁","浩","鑫","欣","佳","文","辉","亮","平","倩","峰","玲","刚","娟","琴","健","霞","龙","华","敏","东","飞","红","彬","宇","博","凯","琳","瑶","晨","薇","睿","帅","甜","萌","菲","莹","冉","青","昊","哲","曦","萱","皓","然","奕","辰","怡","彤","霖","玥","思","雨","子","涵","一","诺","梓","萱","可","悦","乐"},
		LastNames: []string{"王","李","张","刘","陈","杨","赵","黄","周","吴","徐","孙","马","胡","朱","郭","何","罗","高","林","梁","宋","郑","谢","韩","唐","曹","许","邓","冯","蔡","彭","潘","袁","董","苏","卢","蒋","余","杜","叶","程","魏","吕","丁","任","沈","姚","姜","崔","钟","谭","陆","汪","范","金","石","廖","贾","夏","韦","付","方","白","邹","孟","熊","秦","邱","江","尹","薛","闫","段","雷","侯","龙","史","陶","贺","顾","毛","郝","龚","邵","万","钱","严","覃","武","戴","莫","孔","向","汤"},
		Cities: []CityDef{
			{"上海","31"},{"北京","11"},{"深圳","44"},{"广州","44"},{"成都","51"},{"天津","12"},{"武汉","42"},{"东莞","44"},{"西安","61"},{"南京","32"},{"杭州","33"},{"佛山","44"},{"重庆","50"},{"青岛","37"},{"沈阳","21"},{"苏州","32"},{"哈尔滨","23"},{"合肥","34"},{"大连","21"},{"长春","22"},{"厦门","35"},{"无锡","32"},{"济南","37"},{"太原","14"},{"郑州","41"},{"石家庄","13"},{"昆明","53"},{"中山","44"},{"南宁","45"},{"福州","35"},{"长沙","43"},{"宁波","33"},{"兰州","62"},{"临沂","37"},{"惠州","44"},{"温州","33"},{"潍坊","37"},{"淄博","37"},{"唐山","13"},{"绍兴","33"},{"海口","46"},{"徐州","32"},{"洛阳","41"},{"呼和浩特","15"},{"烟台","37"},{"珠海","44"},{"南昌","36"},{"济宁","37"},{"扬州","32"},{"包头","15"},{"廊坊","13"},{"邯郸","13"},{"保定","13"},{"常州","32"},{"株洲","43"},{"襄阳","42"},{"宜昌","42"},{"聊城","37"},{"德州","37"},{"菏泽","37"},{"滨州","37"},{"东营","37"},{"枣庄","37"},{"日照","37"},{"泰安","37"},{"威海","37"},{"泉州","35"},{"漳州","35"},{"南平","35"},{"龙岩","35"},{"三明","35"},{"莆田","35"},{"宁德","35"},{"宝鸡","61"},{"咸阳","61"},{"渭南","61"},{"延安","61"},{"汉中","61"},{"安康","61"},{"商洛","61"},{"铜川","61"},{"绵阳","51"},{"德阳","51"},{"南充","51"},{"宜宾","51"},{"泸州","51"},{"自贡","51"},{"乐山","51"},{"眉山","51"},{"广安","51"},{"达州","51"},{"遂宁","51"},{"内江","51"},{"嘉兴","33"},{"金华","33"},{"台州","33"},{"衢州","33"},{"丽水","33"},{"舟山","33"},{"湖州","33"}},
		Streets: []string{"人民路","解放路","中山路","长安街","东风路","建设路","和平路","文一路","科技路","工业路","文化路","教育路","滨河路","环城路","新华路","光明路","北京路","南京路","广州路","成都路","延安路","淮海路","吴江路","四川北路","四川中路","四川南路","长江路","黄河路","金沙江路","莲花路","芙蓉路","牡丹路","梅花路","兰花路","珠海路","桂花路","樱花路","港湾路","华港路","新建路","衡山路","复兴路","解放北路","解放南路","解放中路","民族大道","文明路","创业大道","科学大道","公园路","体育馆路","博物馆路","图书馆路","科技大道","高新路","金鸡路","育才路","幸福路","康乐路","健康路","文峰路","水乡路","临江路","冰河路","沿江路","海滨路","山海关路","荆州路","楚河路","岭南路","学府路","工农路","人民东路","人民西路","白塔路","飞鹅路","民生路","建设北路","建设南路","长春路","沈阳路","大连路","哈尔滨路","宁波路","温州路","杭州路","福州路","厦门路","东海路","南海路","四海路","金山路","鼓浪路","梧桐路","同济路","惠民路","长安西路","梨园路","桃源路"},
}

}
