#!/usr/bin/env python3
"""
Convert real_addresses.json → real_addresses.go (embedded Go source).
This is the tool users run after editing the JSON to add/remove addresses.

Usage:
    python3 scripts/json_to_go.py
    # reads internal/addrgen/real_addresses.json
    # writes internal/addrgen/real_addresses.go
"""

import json, os, sys
from collections import OrderedDict

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(PROJECT_ROOT, "internal", "addrgen", "real_addresses.json")
GO_PATH = os.path.join(PROJECT_ROOT, "internal", "addrgen", "real_addresses.go")

def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def escape_go(s):
    """Escape a string for Go source code."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")

def generate_go(data):
    """Generate real_addresses.go from JSON data."""
    lines = [
        "// Code generated by scripts/json_to_go.py from real_addresses.json.",
        "// DO NOT EDIT BY HAND - edit the JSON and regenerate.",
        "package addrgen",
        "",
        "func init() {",
        "\trealAddresses = map[string][]cityRealAddrs{",
    ]
    
    for cc in sorted(data.keys()):
        cities = data[cc]
        if not cities:
            continue
        
        lines.append(f'\t\t"{cc}": []cityRealAddrs{{')
        for entry in cities:
            city = entry.get("city", "")
            state = entry.get("state", "")
            addrs = entry.get("addresses", [])
            if not addrs:
                continue
            
            lines.append(f'\t\t\tcityRealAddrs{{City: "{escape_go(city)}", State: "{escape_go(state)}", Addrs: []RealAddress{{')
            for a in addrs:
                hn = escape_go(a.get("h", ""))
                st = escape_go(a.get("s", ""))
                pc = escape_go(a.get("p", ""))
                cn = escape_go(a.get("c", ""))
                lines.append(f'\t\t\t\tRealAddress{{HouseNumber: "{hn}", Street: "{st}", Postcode: "{pc}", CityName: "{cn}"}},')
            lines.append('\t\t\t}},')
        lines.append('\t\t},')
    
    lines.append('\t}')
    lines.append('}')
    lines.append('')
    
    return '\n'.join(lines)

def main():
    if not os.path.exists(JSON_PATH):
        print(f"❌ JSON file not found: {JSON_PATH}")
        print(f"   Run scripts/fetch_real_streets.py first to generate it.")
        sys.exit(1)
    
    data = load_json(JSON_PATH)
    
    # Count stats
    total_addrs = 0
    total_cities = 0
    for cc, cities in data.items():
        for entry in cities:
            n = len(entry.get("addresses", []))
            if n > 0:
                total_cities += 1
                total_addrs += n
    
    go_code = generate_go(data)
    
    with open(GO_PATH, "w", encoding="utf-8") as f:
        f.write(go_code)
    
    size = os.path.getsize(GO_PATH)
    print(f"✅ Generated: {GO_PATH}")
    print(f"   {total_addrs} real addresses across {total_cities} cities in {len(data)} countries")
    print(f"   File size: {size:,} bytes ({go_code.count(chr(10))} lines)")
    print(f"   Build: go build ./cmd/bot/")
    
    # Also print country breakdown
    print(f"\n   Breakdown:")
    for cc, cities in sorted(data.items()):
        c = sum(1 for e in cities if e.get("addresses"))
        a = sum(len(e.get("addresses", [])) for e in cities)
        if c > 0:
            print(f"     {cc}: {a} addrs in {c} cities")

if __name__ == "__main__":
    main()
